## YAML Template.
server:
    port: 8762
spring:
    application:
        name: admin-server
        
--- #Configuration for eureka client        

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
        metadata-map:
            startup: ${random.int} #needed to trigger info and endpoint update after restart
    client:
        registryFetchIntervalInSeconds: 5        
        service-url: 
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
--- #Si hay algun fallo puede ser el service-url cambiarlo por serviceUrl en todos los yml
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS