#see for java tunning https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM161
version: '3.8'
services:
  #Docker Compose creates a virtual network between the services and the DNS name 
  #used for each service is its name: that’s why it’s possible to use eureka-discovery as the hostname.
  registry-discovery:
    container_name: id-eureka
    image: digitalthinking/microservice_docker_eurekaserver:1
    ports:
      - 8761:8761
    environment:        
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         
 ##########################################################################     
 #configuration service
 ##########################################################################  
  configuration:
    container_name: id-config
    image: digitalthinking/microservice_docker_configserver:1
    volumes:
      #this it use because we are using a local github repository /host/path:/container/path use ./ for relative path
      - ./config-server-repo:/tmp/config-server-repo
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server 
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/         
         -DSPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/EnzoNina/git-remote-config.git
         -DSPRING_SECURITY_USER_NAME=admin
         -DSPRING_SECURITY_USER_PASSWORD=admin         
         #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888
      
 ##########################################################################     
 #administration service
 ##########################################################################  
  administration:
    container_name: id-admin
    image: digitalthinking/microservice_docker_adminserver:1   
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server 
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8762:8762
      
 ##########################################################################     
 #apigateway service
 ##########################################################################  
  apigateway:
    container_name: apigateway
    image: digitalthinking/microservice_docker_apigateway:1
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server 
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8080:8080
      
 ##########################################################################     
 #product service
 ##########################################################################  
  product-catalog:
    container_name: bd-product-catalog
    image: digitalthinking/microservice_docker_productservice:1
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/  
         -Dspring.profiles.active=product
    depends_on:
      - registry-discovery
      - configuration
  
      
 ##########################################################################     
 #customer service
 ##########################################################################        
  customer:
    container_name: bd-customer
    image: digitalthinking/microservice_docker_customer:1   
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -Dspring.profiles.active=customer
    depends_on:
      - registry-discovery
      - configuration
    
      
 ##########################################################################     
 #transaction service
 ##########################################################################  
  transactions:
    container_name: bd-transactions
    image: digitalthinking/microservice_docker_transactionservice:1   
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -Dspring.profiles.active=transaction         
    depends_on:
      - registry-discovery
      - configuration
                  
  ##########################################################################
  # Servicio de base de datos MySQL
  ##########################################################################
  mysql_db:
    container_name: mysql
    image: mysql:latest    
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin      
  ##########################################################################
  # PhpMyAdmin service
  ##########################################################################
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - mysql_db